### ISSUE TITLE
v1.0.2 does not contain polyfill.js

### ISSUE THREAD

**Issue by NeilSorensen** [doowb/homedir-polyfill#3]
https://github.com/doowb/homedir-polyfill/commit/b25fbb0b5a02197380a6eb9cee165b05d492b3a9 extracted most of the work of homedir-polyfill from index.js to polyfill.js.

Unfortunately, v1.0.2 of the package only contains index.js, not polyfill.js. Things still work as long as os.homedir is defined, but since the whole point of homedir-polyfill is to make things work when os,homedir is not defined, the current version of this package is kind of useless.

**Comment by doowb** [comment]
Thanks for finding that, I'll get it fixed ASAP.

**Comment by NeilSorensen** [comment]
Thanks for fixing this so fast!
